# Generated from Judilibre taxonomy API
LOCATION_CA = {
  "ca_agen": "Cour d'appel d'Agen",
  "ca_aix_provence": "Cour d'appel d'Aix-en-Provence",
  "ca_amiens": "Cour d'appel d'Amiens",
  "ca_angers": "Cour d'appel d'Angers",
  "ca_basse_terre": "Cour d'appel de Basse-Terre",
  "ca_bastia": "Cour d'appel de Bastia",
  "ca_besancon": "Cour d'appel de Besançon",
  "ca_bordeaux": "Cour d'appel de Bordeaux",
  "ca_bourges": "Cour d'appel de Bourges",
  "ca_caen": "Cour d'appel de Caen",
  "ca_cayenne": "Cour d'appel de Cayenne",
  "ca_chambery": "Cour d'appel de Chambéry",
  "ca_colmar": "Cour d'appel de Colmar",
  "ca_dijon": "Cour d'appel de Dijon",
  "ca_douai": "Cour d'appel de Douai",
  "ca_fort_de_france": "Cour d'appel de Fort-de-France",
  "ca_grenoble": "Cour d'appel de Grenoble",
  "ca_limoges": "Cour d'appel de Limoges",
  "ca_lyon": "Cour d'appel de Lyon",
  "ca_metz": "Cour d'appel de Metz",
  "ca_montpellier": "Cour d'appel de Montpellier",
  "ca_nancy": "Cour d'appel de Nancy",
  "ca_nimes": "Cour d'appel de Nîmes",
  "ca_noumea": "Cour d'appel de Nouméa",
  "ca_orleans": "Cour d'appel d'Orléans",
  "ca_papeete": "Cour d'appel de Papeete",
  "ca_paris": "Cour d'appel de Paris",
  "ca_pau": "Cour d'appel de Pau",
  "ca_poitiers": "Cour d'appel de Poitiers",
  "ca_reims": "Cour d'appel de Reims",
  "ca_rennes": "Cour d'appel de Rennes",
  "ca_riom": "Cour d'appel de Riom",
  "ca_rouen": "Cour d'appel de Rouen",
  "ca_st_denis_reunion": "Cour d'appel de Saint-Denis de la Réunion",
  "ca_toulouse": "Cour d'appel de Toulouse",
  "ca_versailles": "Cour d'appel de Versailles"
}

LOCATION_TJ = {
  "tj47001": "Tribunal judiciaire d'Agen",
  "tj13001": "Tribunal judiciaire d'Aix-en-Provence",
  "tj2a004": "Tribunal judiciaire d'Ajaccio",
  "tj73011": "Tribunal judiciaire d'Albertville",
  "tj81004": "Tribunal judiciaire d'Albi",
  "tj61001": "Tribunal judiciaire d'Alençon",
  "tj30007": "Tribunal judiciaire d'Alès",
  "tj80021": "Tribunal judiciaire d'Amiens",
  "tj49007": "Tribunal judiciaire d'Angers",
  "tj16015": "Tribunal judiciaire d'Angoulême",
  "tj74010": "Tribunal judiciaire d'Annecy",
  "tj61006": "Tribunal judiciaire d'Argentan",
  "tj62041": "Tribunal judiciaire d'Arras",
  "tj32013": "Tribunal judiciaire d'Auch",
  "tj15014": "Tribunal judiciaire d'Aurillac",
  "tj89024": "Tribunal judiciaire d'Auxerre",
  "tj59036": "Tribunal judiciaire d'Avesnes-sur-Helpe",
  "tj84007": "Tribunal judiciaire d'Avignon",
  "tj55029": "Tribunal judiciaire de Bar-le-Duc",
  "tj97105": "Tribunal judiciaire de Basse-Terre",
  "tj2b033": "Tribunal judiciaire de Bastia",
  "tj64102": "Tribunal judiciaire de Bayonne",
  "tj60057": "Tribunal judiciaire de Beauvais",
  "tj90010": "Tribunal judiciaire de Belfort",
  "tj24037": "Tribunal judiciaire de Bergerac",
  "tj25056": "Tribunal judiciaire de Besançon",
  "tj62119": "Tribunal judiciaire de Béthune",
  "tj34032": "Tribunal judiciaire de Béziers",
  "tj41018": "Tribunal judiciaire de Blois",
  "tj93008": "Tribunal judiciaire de Bobigny",
  "tj74042": "Tribunal judiciaire de Bonneville",
  "tj33063": "Tribunal judiciaire de Bordeaux",
  "tj62160": "Tribunal judiciaire de Boulogne-sur-Mer",
  "tj01053": "Tribunal judiciaire de Bourg-en-Bresse",
  "tj18033": "Tribunal judiciaire de Bourges",
  "tj38053": "Tribunal judiciaire de Bourgoin-Jallieu",
  "tj29019": "Tribunal judiciaire de Brest",
  "tj19031": "Tribunal judiciaire de Brive-la-Gaillarde",
  "tj14118": "Tribunal judiciaire de Caen",
  "tj46042": "Tribunal judiciaire de Cahors",
  "tj59122": "Tribunal judiciaire de Cambrai",
  "tj11069": "Tribunal judiciaire de Carcassonne",
  "tj84031": "Tribunal judiciaire de Carpentras",
  "tj81065": "Tribunal judiciaire de Castres",
  "tj97302": "Tribunal judiciaire de Cayenne",
  "tj71076": "Tribunal judiciaire de Chalon-sur-Saône",
  "tj51108": "Tribunal judiciaire de Chalons-en-Champagne",
  "tj73065": "Tribunal judiciaire de Chambéry",
  "tj08105": "Tribunal judiciaire de Charleville-Mézières",
  "tj28085": "Tribunal judiciaire de Chartres",
  "tj36044": "Tribunal judiciaire de Châteauroux",
  "tj52121": "Tribunal judiciaire de Chaumont",
  "tj50129": "Tribunal judiciaire de Cherbourg-en-Cotentin",
  "tj63113": "Tribunal judiciaire de Clermont-Ferrand",
  "tj68066": "Tribunal judiciaire de Colmar",
  "tj60159": "Tribunal judiciaire de Compiègne",
  "tj50147": "Tribunal judiciaire de Coutances",
  "tj94028": "Tribunal judiciaire de Créteil",
  "tj03095": "Tribunal judiciaire de Cusset",
  "tj40088": "Tribunal judiciaire de Dax",
  "tj76217": "Tribunal judiciaire de Dieppe",
  "tj04070": "Tribunal judiciaire de Digne-les-Bains",
  "tj21231": "Tribunal judiciaire de Dijon",
  "tj39198": "Tribunal judiciaire de Dole (chambre détachée)",
  "tj59178": "Tribunal judiciaire de Douai",
  "tj83050": "Tribunal judiciaire de Draguignan",
  "tj59183": "Tribunal judiciaire de Dunkerque",
  "tj88160": "Tribunal judiciaire d'Épinal",
  "tj27229": "Tribunal judiciaire d'Évreux",
  "tj91228": "Tribunal judiciaire d'Évry",
  "tj09122": "Tribunal judiciaire de Foix",
  "tj77186": "Tribunal judiciaire de Fontainebleau",
  "tj97209": "Tribunal judiciaire de Fort-de-France",
  "tj05061": "Tribunal judiciaire de Gap",
  "tj06069": "Tribunal judiciaire de Grasse",
  "tj38185": "Tribunal judiciaire de Grenoble",
  "tj23096": "Tribunal judiciaire de Guéret",
  "tj22070": "Tribunal judiciaire de Guingamp (chambre détachée)",
  "tj98811": "Tribunal judiciaire de Kone (section détachée)",
  "tj85191": "Tribunal judiciaire de La Roche-sur-Yon",
  "tj17300": "Tribunal judiciaire de La Rochelle",
  "tj02408": "Tribunal judiciaire de Laon",
  "tj53130": "Tribunal judiciaire de Laval",
  "tj76351": "Tribunal judiciaire du Havre",
  "tj72181": "Tribunal judiciaire du Mans",
  "tj43157": "Tribunal judiciaire du Puy-en-Velay",
  "tj85194": "Tribunal judiciaire des Sables-d'Olonne",
  "tj33243": "Tribunal judiciaire de Libourne",
  "tj59350": "Tribunal judiciaire de Lille",
  "tj87085": "Tribunal judiciaire de Limoges",
  "tj14366": "Tribunal judiciaire de Lisieux",
  "tj39300": "Tribunal judiciaire de Lons-le-Saunier",
  "tj56121": "Tribunal judiciaire de Lorient",
  "tj69123": "Tribunal judiciaire de Lyon",
  "tj71270": "Tribunal judiciaire de Mâcon",
  "tj97611": "Tribunal judiciaire de Mamoudzou",
  "tj47157": "Tribunal judiciaire de Marmande (chambre détachée)",
  "tj13055": "Tribunal judiciaire de Marseille",
  "tj98613": "Tribunal judiciaire de Mata-Utu",
  "tj77284": "Tribunal judiciaire de Meaux",
  "tj77288": "Tribunal judiciaire de Melun",
  "tj48095": "Tribunal judiciaire de Mende",
  "tj57463": "Tribunal judiciaire de Metz",
  "tj12145": "Tribunal judiciaire de Millau (chambre détachée)",
  "tj40192": "Tribunal judiciaire de Mont-de-Marsan",
  "tj45208": "Tribunal judiciaire de Montargis",
  "tj82121": "Tribunal judiciaire de Montauban",
  "tj25388": "Tribunal judiciaire de Montbéliard",
  "tj03185": "Tribunal judiciaire de Montluçon",
  "tj34172": "Tribunal judiciaire de Montpellier",
  "tj03190": "Tribunal judiciaire de Moulins",
  "tj68224": "Tribunal judiciaire de Mulhouse",
  "tj54395": "Tribunal judiciaire de Nancy",
  "tj92050": "Tribunal judiciaire de Nanterre",
  "tj44109": "Tribunal judiciaire de Nantes",
  "tj11262": "Tribunal judiciaire de Narbonne",
  "tj58194": "Tribunal judiciaire de Nevers",
  "tj06088": "Tribunal judiciaire de Nice",
  "tj30189": "Tribunal judiciaire de Nîmes",
  "tj79191": "Tribunal judiciaire de Niort",
  "tj98818": "Tribunal judiciaire de Nouméa",
  "tj45234": "Tribunal judiciaire d'Orléans",
  "tj98735": "Tribunal judiciaire de Papeete",
  "tj75056": "Tribunal judiciaire de Paris",
  "tj64445": "Tribunal judiciaire de Pau",
  "tj24322": "Tribunal judiciaire de Périgueux",
  "tj66136": "Tribunal judiciaire de Perpignan",
  "tj97120": "Tribunal judiciaire de Pointe-à-Pitre",
  "tj86194": "Tribunal judiciaire de Poitiers",
  "tj95500": "Tribunal judiciaire de Pontoise",
  "tj07186": "Tribunal judiciaire de Privas",
  "tj29232": "Tribunal judiciaire de Quimper",
  "tj51454": "Tribunal judiciaire de Reims",
  "tj35238": "Tribunal judiciaire de Rennes",
  "tj42187": "Tribunal judiciaire de Roanne",
  "tj12202": "Tribunal judiciaire de Rodez",
  "tj76540": "Tribunal judiciaire de Rouen",
  "tj22278": "Tribunal judiciaire de Saint-Brieuc",
  "tj97411": "Tribunal judiciaire de Saint-Denis de La Réunion",
  "tj42218": "Tribunal judiciaire de Saint-Etienne",
  "tj31483": "Tribunal judiciaire de Saint-Gaudens",
  "tj35288": "Tribunal judiciaire de Saint-Malo",
  "tj44184": "Tribunal judiciaire de Saint-Nazaire",
  "tj62765": "Tribunal judiciaire de Saint-Omer",
  "tj97416": "Tribunal judiciaire de Saint-Pierre de La Réunion",
  "tj02691": "Tribunal judiciaire de Saint-Quentin",
  "tj97311": "Tribunal judiciaire de Saint-Laurent-Du-Maroni (chambre détachée)",
  "tj97801": "Tribunal judiciaire de Saint-Martin (chambre détachée)",
  "tj17415": "Tribunal judiciaire de Saintes",
  "tj57631": "Tribunal judiciaire de Sarreguemines",
  "tj49328": "Tribunal judiciaire de Saumur",
  "tj67437": "Tribunal judiciaire de Saverne",
  "tj60612": "Tribunal judiciaire de Senlis",
  "tj89387": "Tribunal judiciaire de Sens",
  "tj02722": "Tribunal judiciaire de Soissons",
  "tj67482": "Tribunal judiciaire de Strasbourg",
  "tj13108": "Tribunal judiciaire de Tarascon",
  "tj65440": "Tribunal judiciaire de Tarbes",
  "tj57672": "Tribunal judiciaire de Thionville",
  "tj74281": "Tribunal judiciaire de Thonon-les-Bains",
  "tj83137": "Tribunal judiciaire de Toulon",
  "tj31555": "Tribunal judiciaire de Toulouse",
  "tj37261": "Tribunal judiciaire de Tours",
  "tj10387": "Tribunal judiciaire de Troyes",
  "tj19272": "Tribunal judiciaire de Tulle",
  "tj54099": "Tribunal judiciaire de Val de Briey",
  "tj26362": "Tribunal judiciaire de Valence",
  "tj59606": "Tribunal judiciaire de Valenciennes",
  "tj56260": "Tribunal judiciaire de Vannes",
  "tj55545": "Tribunal judiciaire de Verdun",
  "tj78646": "Tribunal judiciaire de Versailles",
  "tj70550": "Tribunal judiciaire de Vesoul",
  "tj38544": "Tribunal judiciaire de Vienne",
  "tj69264": "Tribunal judiciaire de Villefranche-sur-Saône"
}

LOCATION_TCOM = {
  "1001": "Tribunal de commerce de Troyes",
  "1101": "Tribunal de commerce de Carcassonne",
  "1104": "Tribunal de commerce de Narbonne",
  "1203": "Tribunal de commerce de Rodez",
  "1301": "Tribunal de commerce d'Aix-en-Provence",
  "1303": "Tribunal des activités économiques de Marseille",
  "1304": "Tribunal de commerce de Salon-de-Provence",
  "1305": "Tribunal de commerce de Tarascon",
  "1402": "Tribunal de commerce de Caen",
  "1407": "Tribunal de commerce de Lisieux",
  "1501": "Tribunal de commerce d'Aurillac",
  "1601": "Tribunal de commerce d'Angoulême",
  "1704": "Tribunal de commerce de La Rochelle",
  "1708": "Tribunal de commerce de Saintes",
  "1801": "Tribunal de commerce de Bourges",
  "1901": "Tribunal de commerce de Brive-la-Gaillarde",
  "2001": "Tribunal de commerce d'Ajaccio",
  "2002": "Tribunal de commerce de Bastia",
  "2104": "Tribunal de commerce de Dijon",
  "2202": "Tribunal des activités économiques de Saint-Brieuc",
  "2301": "Tribunal de commerce de Guéret",
  "2401": "Tribunal de commerce de Bergerac",
  "2402": "Tribunal de commerce de Périgueux",
  "2501": "Tribunal de commerce de Besançon",
  "2602": "Tribunal de commerce de Romans",
  "2701": "Tribunal de commerce de Bernay",
  "2702": "Tribunal de commerce d'Évreux",
  "2801": "Tribunal de commerce de Chartres",
  "2901": "Tribunal de commerce de Brest",
  "2903": "Tribunal de commerce de Quimper",
  "3003": "Tribunal de commerce de Nîmes",
  "3102": "Tribunal de commerce de Toulouse",
  "3201": "Tribunal de commerce d'Auch",
  "3302": "Tribunal de commerce de Bordeaux",
  "3303": "Tribunal de commerce de Libourne",
  "3402": "Tribunal de commerce de Béziers",
  "3405": "Tribunal de commerce de Montpellier",
  "3501": "Tribunal de commerce de Rennes",
  "3502": "Tribunal de commerce de Saint-Malo",
  "3601": "Tribunal de commerce de Châteauroux",
  "3701": "Tribunal de commerce de Tours",
  "3801": "Tribunal de commerce de Grenoble",
  "3802": "Tribunal de commerce de Vienne",
  "3902": "Tribunal de commerce de Lons-le-Saunier",
  "4001": "Tribunal de commerce de Dax",
  "4002": "Tribunal de commerce de Mont-de-Marsan",
  "4101": "Tribunal de commerce de Blois",
  "4201": "Tribunal de commerce de Roanne",
  "4202": "Tribunal de commerce de Saint-Etienne",
  "4302": "Tribunal de commerce du Puy-en-Velay",
  "4401": "Tribunal de commerce de Nantes",
  "4402": "Tribunal de commerce de Saint-Nazaire",
  "4502": "Tribunal de commerce d'Orléans",
  "4601": "Tribunal de commerce de Cahors",
  "4701": "Tribunal de commerce d'Agen",
  "4801": "Tribunal de commerce de Mende",
  "4901": "Tribunal de commerce d'Angers",
  "5001": "Tribunal de commerce de Cherbourg",
  "5002": "Tribunal de commerce de Coutances",
  "5101": "Tribunal de commerce de Chalons-en-Champagne",
  "5103": "Tribunal de commerce de Reims",
  "5201": "Tribunal de commerce de Chaumont",
  "5301": "Tribunal de commerce de Laval",
  "5401": "Tribunal de commerce de Briey",
  "5402": "Tribunal des activités économiques de Nancy",
  "5501": "Tribunal de commerce de Bar-le-Duc",
  "5601": "Tribunal de commerce de Lorient",
  "5602": "Tribunal de commerce de Vannes",
  "5802": "Tribunal de commerce de Nevers",
  "5902": "Tribunal de commerce de Dunkerque",
  "5906": "Tribunal de commerce de Valenciennes",
  "5910": "Tribunal de commerce de Lille Métropole",
  "5952": "Tribunal de commerce de Douai",
  "6001": "Tribunal de commerce de Beauvais",
  "6002": "Tribunal de commerce de Compiègne",
  "6101": "Tribunal de commerce d'Alençon",
  "6201": "Tribunal de commerce d'Arras",
  "6202": "Tribunal de commerce de Boulogne-sur-Mer",
  "6303": "Tribunal de commerce de Clermont-Ferrand",
  "6401": "Tribunal de commerce de Bayonne",
  "6403": "Tribunal de commerce de Pau",
  "6502": "Tribunal de commerce de Tarbes",
  "6601": "Tribunal de commerce de Perpignan",
  "6901": "Tribunal des activités économiques de Lyon",
  "6903": "Tribunal de commerce de Villefranche-sur-Saône - Tarare",
  "7001": "Tribunal de commerce de Vesoul - Gray",
  "7102": "Tribunal de commerce de Chalon-sur-Saône",
  "7106": "Tribunal de commerce de Mâcon",
  "7202": "Tribunal des activités économiques du Mans",
  "7301": "Tribunal de commerce de Chambéry",
  "7401": "Tribunal de commerce d'Annecy",
  "7402": "Tribunal de commerce de Thonon-les-Bains",
  "7501": "Tribunal des activités économiques de Paris",
  "7601": "Tribunal de commerce de Dieppe",
  "7606": "Tribunal des activités économiques du Havre",
  "7608": "Tribunal de commerce de Rouen",
  "7701": "Tribunal de commerce de Meaux",
  "7702": "Tribunal de commerce de Melun",
  "7801": "Tribunal de commerce d'Évry",
  "7802": "Tribunal de commerce de Pontoise",
  "7803": "Tribunal des activités économiques de Versailles",
  "7901": "Tribunal de commerce de Niort",
  "8002": "Tribunal de commerce d'Amiens",
  "8101": "Tribunal de commerce d'Albi",
  "8102": "Tribunal de commerce de Castres",
  "8201": "Tribunal de commerce de Montauban",
  "8302": "Tribunal de commerce de Draguignan",
  "8303": "Tribunal de commerce de Fréjus",
  "8305": "Tribunal de commerce de Toulon",
  "8401": "Tribunal des activités économiques d'Avignon",
  "8501": "Tribunal de commerce de La Roche-sur-Yon",
  "8602": "Tribunal de commerce de Poitiers",
  "8701": "Tribunal des activités économiques de Limoges",
  "8801": "Tribunal de commerce d'Épinal",
  "8901": "Tribunal des activités économiques d'Auxerre",
  "8903": "Tribunal de commerce de Sens",
  "9001": "Tribunal de commerce de Belfort",
  "9201": "Tribunal des activités économiques de Nanterre",
  "9301": "Tribunal de commerce de Bobigny",
  "9401": "Tribunal de commerce de Créteil",
  "9711": "Tribunal de commerce de Basse-Terre",
  "9712": "Tribunal de commerce de Pointe-à-Pitre",
  "9721": "Tribunal de commerce de Fort-de-France",
  "9731": "Tribunal de commerce de Cayenne",
  "9741": "Tribunal de commerce de Saint-Denis de La Réunion",
  "9742": "Tribunal de commerce de Saint-Pierre de La Réunion",
  "9761": "Tribunal de commerce de Mamoudzou",
  "0601": "Tribunal de commerce d'Antibes",
  "0702": "Tribunal de commerce d'Aubenas",
  "0101": "Tribunal de commerce de Bourg-en-Bresse",
  "0602": "Tribunal de commerce de Cannes",
  "0301": "Tribunal de commerce de Cusset",
  "0901": "Tribunal de commerce de Foix",
  "0501": "Tribunal de commerce de Gap",
  "0603": "Tribunal de commerce de Grasse",
  "0401": "Tribunal de commerce de Manosque",
  "0303": "Tribunal de commerce de Montluçon",
  "0605": "Tribunal de commerce de Nice",
  "0202": "Tribunal de commerce de Saint-Quentin",
  "0802": "Tribunal de commerce de Sedan",
  "0203": "Tribunal de commerce de Soissons"
}
